### ISSUE TITLE
 更新字库以后出错

### ISSUE THREAD

**Issue by yi89521** [qichuan/android-opencc#10]
大神，我在资源文件下面的txt里面添加了几个词，然后再转换的时候  就会出现: /buildbot/src/googleplex-android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type opencc::InvalidTextDictionary" failed  错误，是我更新字库的方式不对，还是什么原因造成的

**Comment by qichuan** [comment]
你把添了字的资源文件发来看看？

**Comment by yi89521** [comment]
附件是添加了字的资源文件，滑鼠后面的几个词是我新添加的。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qichuan (Sean) ZHANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 晚上8:07
收件人:&nbsp;"qichuan/android-opencc"<android-opencc@noreply.github.com&gt;;
抄送:&nbsp;"﹏剧情再美、终究是戏ゝ"<328843533@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qichuan/android-opencc]  更新字库以后出错 (#10)




你把添了字的资源文件发来看看？

**Comment by qichuan** [comment]
@yi89521 没有看到附件，要不在你到 fork 分支里上传资源，把链接发给我。

**Comment by yi89521** [comment]
你好，我已经创建分支，把我修改后的资源文件上传了。。https://github.com/yi89521/android-opencc/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qichuan (Sean) ZHANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 中午1:46
收件人:&nbsp;"qichuan/android-opencc"<android-opencc@noreply.github.com&gt;;
抄送:&nbsp;"﹏剧情再美、终究是戏ゝ"<328843533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [qichuan/android-opencc]  更新字库以后出错 (#10)




@yi89521 没有看到附件，要不在你到 fork 分支里上传资源，把链接发给我。

**Comment by qichuan** [comment]
<img width="344" alt="Screen Shot 2019-12-17 at 4 46 32 PM" src="https://user-images.githubusercontent.com/410850/70979569-cf450880-20ec-11ea-9d7d-e1869ee2bab3.png">
收貨人 前面多了一个空格

看你的错误日志是在编译的时候出错，而不是运行的时候。我本地跑了一下无法复现你的问题。请问你的测试机型号是什么？armv7 还是 arm_64 芯片？

**Comment by yi89521** [comment]
小米9&nbsp; arm64&nbsp; ，我用网易mumu模拟器也会出现在这错误，不是在编译阶段，运行的时候出现的错误。。对于gradle版本没有什么限制吧？我用的是4.4的版本。。



这是运行以后的错误日志
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qichuan (Sean) ZHANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 下午4:48
收件人:&nbsp;"qichuan/android-opencc"<android-opencc@noreply.github.com&gt;;
抄送:&nbsp;"﹏剧情再美、终究是戏ゝ"<328843533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [qichuan/android-opencc]  更新字库以后出错 (#10)





 收貨人 前面多了一个空格 
看你的错误日志是在编译的时候出错，而不是运行的时候。我本地跑了一下无法复现你的问题。请问你的测试机型号是什么？armv7 还是 arm_64 芯片？

**Comment by qichuan** [comment]
我也试了 MuMu 模拟器，无法复现你的问题。

我使用  Gradle model version=5.4.1, NDK version=20.1.5948944，你更新试试？

**Comment by yi89521** [comment]
我找到原因啦，字典的连个词中间 用的应该\t 转义字符，我是直接敲的空格





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qichuan (Sean) ZHANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上9:05
收件人:&nbsp;"qichuan/android-opencc"<android-opencc@noreply.github.com&gt;;
抄送:&nbsp;"﹏剧情再美、终究是戏ゝ"<328843533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [qichuan/android-opencc]  更新字库以后出错 (#10)




我也试了 MuMu 模拟器，无法复现你的问题。
 
我使用  Gradle model version=5.4.1, NDK version=20.1.5948944，你更新试试？

**Comment by qichuan** [comment]
太好了，这样我就关闭这个 issue 了。有问题随时联系。
